# Generated by Django 4.2.6 on 2023-10-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('is_solved', models.BooleanField(default=False)),
                ('service', models.CharField(choices=[('ux-ui', 'ux-ui'), ('web-development', 'web-development'), ('internet-platform', 'internet-platform'), ('mobile-development', 'mobile-development')], max_length=100)),
                ('web_development', models.BooleanField(default=False)),
                ('ux_ui', models.BooleanField(default=False)),
                ('internet_platform', models.BooleanField(default=False)),
                ('mobile_development', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
