# Generated by Django 4.2.6 on 2023-11-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='positioning',
            field=models.CharField(blank=True, choices=[('left_top', 'Left Top'), ('right_top', 'Right Top')], max_length=20, null=True),
        ),
    ]
