# Generated by Django 4.2.6 on 2023-12-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_portfolio_positioning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='positioning',
        ),
    ]
